### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by maylea23**
Hello! I've already finished the translation and I really enjoyed it :)
Please let me know if I made any mistake and I'll make the necessary changes. I'm not familiar with GitHub workflow so I'm not sure I'm doing the right things :)

Best,
Laura

### CODE REVIEW

**Comment by ufb** [comment]
Awesome, thanks a lot! :)
I see you created a branch and did a pull request for your forked repo (/maylea23/Textmarker/). Can you merge your commit into master? Only you have write access. After that we can create a cross-fork pull request from your master branch into the main repo (on /ufb/Textmarker/)

**Comment by maylea23** [comment]
yes sure, what do I have to do exactly? 
Thank you :)

**Comment by ufb** [comment]
On this page here do you see a green button at the bottom saying "merge"? If yes: Just click and confirm ;)

**Comment by ufb** [comment]
Oh, just saw that you've overwritten the English messages - Sorry, I should have mentioned that the Italian translation needs its own folder and file: /extension/_locales/it/message.json
But don't worry, I can create it and copy-paste your translations in there;) So no need for a merge of this pull request

Also, I noticed that your branches master and maylea23-patch-1 only differ in one word that was added, so no need for this pull request here.

Would you prefer me to copy-paste your translations into the main repository or would you like to do the changes yourself so that you appear as a "contributor"?
You could just create the folder "it" inside _locales and inside that folder (it) create a file "message.json" and then just copy-paste the translations into this file. After that I can create a pull request and cherry-pick this last commit of yours into the main repo:)

**Comment by maylea23** [comment]
Hi :), I've created a folder 'it' inside _locales and the file 'message.json in it, then copied the translation into it. Can you see that? Do I have to do anything else? Thanks for your help with this!!

**Comment by ufb** [comment]
Hi, thanks a lot! I cherry-picked your last commit - all done now:)

contributors

The Italian translations will be part of next release (probably in a few weeks)

**Comment by maylea23** [comment]
Excellent! Have a nice week ahead!

**Pull request merged**
